# Stage 1: Build app with Node
FROM node:20.19.0-slim AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve med nginx
FROM nginx:alpine

# Fjern default nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Kopiér fra build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Eksponer port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
