services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: calcalc-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.prod
    environment:
      - HOST=0.0.0.0
    restart: always
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: calcalc-frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env.prod
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

