services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calcalc-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: calcalc-frontend
    ports:
      - "80:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
