services:
  backend:
    build:
      context: .
      dockerfile: ./backend/dockerfile
    container_name: calcalc-backend
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - FLASK_DEBUG=False
      - SECRET_KEY=your-production-secret-key-here
      - USE_HTTPS=false
      - CORS_ORIGINS=https://78.47.227.143,http://localhost:3000,http://127.0.0.1:3000
      - PORT=5000
    restart: always
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    container_name: calcalc-frontend
    ports:
      - "443:443"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge